categories:
  - title: "⚠ Breaking Changes"
    labels:
      - "breaking-change"
  - title: "⬆️ Dependencies"
    collapse-after: 1
    labels:
      - "dependencies"
template: |
  ## What's Changed

  $CHANGES
