sudo: false
matrix:
  fast_finish: true
  include:
    - python: "3.7"
      env: TOXENV=py37
    - python: "3.8"
      env: TOXENV=py38
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install --upgrade pip setuptools wheel cython
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - python3 setup.py develop
  - pip install -U tox coveralls
language: python
script:
  - py.test
  - flake8
  - travis_wait tox
after_success: coveralls
